services:
  taskmanager:
    image: postgres:latest  
    container_name: taskmanager_db  
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - "5432:5432"  
    volumes:
      - ./taskmanager_data:/var/lib/postgresql/data  
    networks:
      - taskmanager_network  

  adminer:
    image: adminer:latest  
    container_name: adminer 
    environment:
      ADMINER_DEFAULT_SERVER: taskmanager_db  # Conectar por defecto al servicio de PostgreSQL
    ports:
      - "8080:8080"  # Adminer estará disponible en http://localhost:8080
    depends_on:
      - taskmanager  
    networks:
      - taskmanager_network  

volumes:
  taskmanager_data:
    driver: local  

networks:
  taskmanager_network:
    driver: bridge  
